# Header

menu:
  主页: '/'
  归档: '/archives/'
  读书: '/reading/'
  关于: '/about/'

# SubNav
subnav:
  github: "https://github.com/fan-haobai"
  weibo: "http://weibo.com/u/3364717814"
  rss: "https://www.fanhaobai.com/atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:i@fanhaobai.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: '/atom.xml'

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: '/'

# 版权信息
copyright: 'fanhaobai.com - 京ICP备16061259号'

# Content

# 文章太长，截断按钮文字
excerpt_link:
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: ''
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: ''
# 微信二维码图片地址
weixin: ''

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: '/favicon.ico'

#你的头像url
avatar: 'https://img0.fanhaobai.com/header.jpg'

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus:
  shortname: 'fanhaobai'
  api: '//disqus.fanhaobai.com'

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#5788AA'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '搜索'
  friends: '友链'
  #aboutme: '关于我'

# dns预获取
dns_prefetch:
  0: 'www.fanhaobai.com'
  1: 'img.fanhaobai.com'
  2: 'img0.fanhaobai.com'
  3: 'img1.fanhaobai.com'
  4: 'img2.fanhaobai.com'
  5: 'img3.fanhaobai.com'
  6: 'img4.fanhaobai.com'
  7: 'img5.fanhaobai.com'
  8: 'disqus.fanhaobai.com'
  9: 'cdn.bootcss.com'
  10: 'c.disquscdn.com'
  11: 'assets-cdn.github.com'
  12: 'cn.gravatar.com'
  13: 'uploads.disquscdn.com'

friends:
  美团技术点评: 'http://tech.meituan.com'
  阿里云中间件: 'http://jm.taobao.org'
  风雪之隅: 'http://www.laruence.com'
  Rango: 'http://rango.swoole.com'
  老叶茶馆: 'http://imysql.com'
  十年踪迹: 'https://www.h5jun.com'
  信海龙: 'http://www.bo56.com'
  凯冰科技: 'http://www.zkbhj.com'
  xiaoT: 'http://www.xiaot123.com'
  嗯VIEW: 'https://www.umview.com'
  狂奔的蜗牛: 'https://www.host900.com'
  奔赴: 'http://www.libenfu.com'

#aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家
